---
- name: Check for windows updates
  hosts: windows
  become: false
  gather_facts: false
  tasks:
  - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
    win_updates:
      category_names: 
        - SecurityUpdates
        - CriticalUpdates
        - DefinitionUpdates
        - UpdateRollups
      state: searched
      log_path: C:\ansible_wu.txt
    register: output

  - name: display output
    debug:
      var: output

 
