---
- name: Check for windows updates
  hosts: windows
  become: false
  gather_facts: false
  tasks:
  - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
    win_updates:
      category_names: 
        - SecurityUpdates
        - CriticalUpdates
        - DefinitionUpdates
        - UpdateRollups
      state: searched
      log_path: C:\ansible_wu.txt
    register: output

  - name: display output
    debug:
      var: output

  - name: Install all security, critical, and rollup updates
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - DefinitionUpdates
        - UpdateRollups
      reboot: yes
    register: print

  - name: Print Installed Updates
    debug:
      var: print

  - name: Reboot when it is required
    win_reboot:
    when: print.reboot_required    
