---
- name: Check IBM Cloud VPC VSI
  hosts: localhost
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml
        
    - name: Retrieve image list
      ibm_is_images_info:
      register: images_list
      
    - name: Check for existing VSI
      ibm_is_instance_info:
        name: "{{ vsi_name }}"
      failed_when:
        - vsi.rc != 0
        - '"No Instance found" not in vsi.stderr'
      register: vsi  
