---
- name: List VPC Images 
  hosts: localhost
  collections:
   - ibm.cloudcollection

  tasks:
  
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yaml
    - ibm_is_images_info:
      register: images_list

    - debug:
        var: images_list.resource.images |
             items2dict(key_name='name', value_name='id')
