---
- name: Check for windows updates
  hosts: windows
  become: false
  gather_facts: false
  tasks:
  - name: Install all security, critical, and rollup updates
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - DefinitionUpdates
        - UpdateRollups
        - Updates
        - QualityUpdates
      reboot: yes
    register: print
  - name: Print Installed Updates
    debug:
      var: print

  - name: "[{{ inventory_hostname }}] Run Update Session Orchestrator check to clear GUI cached results"
    win_shell: |
      UsoClient RefreshSettings
      UsoClient ScanInstallWait     

  - name: Reboot when it is required
    win_reboot:
    when: print.reboot_required    
