---
- name: WINDOWS AUTOMATION DEMO
  hosts: windows
  become: false
  gather_facts: true
  tasks:
  - name: CREATE USER bob
    win_user:
      name: bob
      password: B0b123$
      state: present
      groups:
        - Users
